#!/usr/bin/env python3
"""Builds 16-colour PC-98 style palettes for each background and writes them
to game/palettes_generated.rpy.

Real PC-98 games shipped one hand-picked palette per scene (16 colours chosen
from the 4096-colour 12-bit hardware space). This script emulates the artist:
median-cut quantisation on a downscaled copy of the image, farthest-point
selection so highlights and accents survive on dark images, and every colour
snapped to 4 bits per channel so it is a legal PC-98 colour. Index 0 is always
black.

A "_night" variant is derived register by register (cold, dark shift of each
day colour), so a day -> night change is a pure palette-register swap: every
pixel keeps its colour index, only the register value changes - exactly how
PC-98 games did night scenes and fades.

Requires Pillow. Run from the project root:  python3 tools/make_palettes.py
"""
import glob
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES = os.path.join(ROOT, "game", "images")
OUT = os.path.join(ROOT, "game", "palettes_generated.rpy")


def to_4bit(rgb):
    """Snap an 8-bit colour to the PC-98 4-bit-per-channel grid."""
    return tuple(int(round(c / 17.0)) * 17 for c in rgb)


def night_shift(rgb):
    """Cold, dark version of one palette register (moonlight)."""
    r, g, b = rgb
    lum = 0.299 * r + 0.587 * g + 0.114 * b
    r = 0.30 * r + 0.10 * lum
    g = 0.35 * g + 0.15 * lum
    b = 0.55 * b + 0.30 * lum + 20
    return to_4bit((min(255, r), min(255, g), min(255, b)))


def palette_for(im, colors=16):
    """Median-cut to 48 candidates, snap to 4 bits, then farthest-point
    selection weighted by pixel count."""
    small = im.convert("RGB").resize((320, 180), Image.LANCZOS)
    q = small.quantize(colors=48, method=Image.Quantize.MEDIANCUT)
    raw = q.getpalette()[: 48 * 3]
    counts = {}
    for n, idx in q.getcolors():
        c = to_4bit(raw[idx * 3:idx * 3 + 3])
        counts[c] = counts.get(c, 0) + n

    def dist(a, b):
        return 0.30 * (a[0] - b[0]) ** 2 + 0.59 * (a[1] - b[1]) ** 2 + 0.11 * (a[2] - b[2]) ** 2

    chosen = [(0, 0, 0)]
    counts.pop((0, 0, 0), None)
    while len(chosen) < colors and counts:
        best = max(counts, key=lambda c: min(dist(c, k) for k in chosen) * (counts[c] ** 0.35))
        chosen.append(best)
        counts.pop(best)
    for filler in [(255, 255, 255), (136, 136, 136), (68, 68, 68), (204, 204, 204)]:
        if len(chosen) >= colors:
            break
        if filler not in chosen:
            chosen.append(filler)
    return sorted(chosen, key=lambda c: 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2])


## Scene composites: background + character sprite, so the 16 colours are
## shared between both (what a PC-98 artist would have done for that scene).
COMPOSITES = {
    "cafe_claire": ("bg_cafe.webp", "claire.webp"),
    "sunset_claire": ("bg_sunset.webp", "claire.webp"),
    "candles_claire": ("bg_candles.webp", "claire.webp"),
    "rooftop_claire": ("bg_rooftop.webp", "claire.webp"),
}


def composite(bg_name, sprite_name, screen=(1920, 1080)):
    bg = Image.open(os.path.join(IMAGES, bg_name)).convert("RGBA")
    z = screen[1] / float(bg.height)
    bg = bg.resize((int(round(bg.width * z)), screen[1]), Image.LANCZOS)
    x0 = max(0, (bg.width - screen[0]) // 2)
    bg = bg.crop((x0, 0, x0 + screen[0], screen[1]))
    sp = Image.open(os.path.join(IMAGES, sprite_name)).convert("RGBA")
    zoom = screen[1] / float(sp.height)
    sp = sp.resize((int(sp.width * zoom), screen[1]), Image.LANCZOS)
    bg.alpha_composite(sp, ((screen[0] - sp.width) // 2, screen[1] - sp.height))
    return bg.convert("RGB")


def main():
    entries = []
    for path in sorted(glob.glob(os.path.join(IMAGES, "bg_*.webp"))):
        name = os.path.splitext(os.path.basename(path))[0][3:]
        im = Image.open(path).convert("RGB")
        day = palette_for(im)
        entries.append((name, day))
        entries.append((name + "_night", [night_shift(c) for c in day]))
    for name, (bg_name, sprite_name) in sorted(COMPOSITES.items()):
        day = palette_for(composite(bg_name, sprite_name))
        entries.append((name, day))
        entries.append((name + "_night", [night_shift(c) for c in day]))

    # Swatch strips (game/images/pal_<name>.png) for the demo video.
    for name, cols in entries:
        strip = Image.new("RGBA", (16 * 66 - 2, 64), (0, 0, 0, 0))
        for i, c in enumerate(cols):
            strip.paste(Image.new("RGBA", (64, 64), c + (255,)), (i * 66, 0))
        strip.save(os.path.join(IMAGES, "pal_%s.png" % name))

    with open(OUT, "w") as f:
        f.write("## GENERATED by tools/make_palettes.py - do not edit by hand.\n")
        f.write("## One 16-colour palette per background (4 bits per channel),\n")
        f.write("## plus a *_night variant derived register by register.\n\n")
        f.write("init -5 python:\n")
        f.write("    pc98_palettes.update({\n")
        for name, cols in entries:
            f.write('        "%s": [\n' % name)
            for r, g, b in cols:
                f.write("            (%.4f, %.4f, %.4f),  # #%02x%02x%02x\n" % (r / 255.0, g / 255.0, b / 255.0, r, g, b))
            f.write("        ],\n")
        f.write("    })\n")
    print("wrote", OUT, "with", len(entries), "palettes")


if __name__ == "__main__":
    main()
